repository: netchira/netchira.github.io

markdown: kramdown
highlighter: rouge

permalink: none

theme: jekyll-theme-architect

url: "https://netchira.github.io" 
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-feed
