repository: netchira/netchira.github.io

markdown: kramdown
highlighter: rouge

permalink: none

theme: jekyll-theme-cayman

url: "https://netchira.github.io" 
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-feed

sitemap: 
 lastmod: 2018-03-24
 priority: 1.0
 changefreq: weekly
 exclude: "https://netchira.github.io/blog/dairy_March2018.html"